### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by EvaMart** [inab/openEBench-nuxt#616]
According to the README: 
> The git workflow for building and pushing the Docker Image for https://dev-openebench.bsc.es/ and https://openebench.bsc.es/ is triggered by a push or pull_request to the master branch. 
>
> Important: Only tagging a master branch with e.g. v1.0.0 will set the latesttag on the docker image and therefore enable Auto Deployment.

I am afraid this is not true. We have made several merges to master that led to the deployment of that code in `production`. Not in `dev`.

In the workflow specification:
```yml
name: Docker Image CI production

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'
```

Either one of the two conditions triggers the workflow. 

We have two options:

- Modify workflow: force the two conditions to be met to build the docker image and deploy it.
- Modify readme: so the CI remains as it is, but it is explained correctly in the readme. 

Let's correct this because as it is now, it can lead to accidentally pushing stuff to production when there was no intention to do so.
